name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print readme content
        run: cat README.md
      - name: Print greeting
        run: echo "Done - bye!"
